version: '3.7'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-container
    restart: always
    environment:
      - MONGO_INITDB_DATABASE=projetdb
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=testpass
    ports:
      - 27217:27217
    volumes:
        - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
