server:
  host: 0.0.0.0
  port: 3000
swagger:
  title: My new Project
  description: The API description
  version: 1.0
  tag: documentation
  tagAuth: authentification
  tagAnimals: animals
  tagBenevoles: benevoles
  tagRefuge: refuge
  path: documentation
mongodb:
  uri: mongodb://0.0.0.0:27017/adoptpetdb
  options:
    useNewUrlParser: true
    useUnifiedTopology: true
    useFindAndModify: false
